// Generates docs/connectors.md from each connector's own metadata, so the catalog cannot drift from the code.
//   node scripts/catalog.mjs          write the file (needs `pnpm build` first)
//   node scripts/catalog.mjs --check  fail if it is out of date (CI)
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { pathToFileURL } from "node:url"

const check = process.argv.includes("--check")
const root = "dist/connectors"
if (!existsSync(root)) {
  console.error("dist/connectors not found: run `pnpm build` first.")
  process.exit(2)
}

const authLabel = (auth) =>
  ({ oauth2: "OAuth 2.0 or token", bearer: "API token", apiKey: "API key", basic: "Username and password / API key" })[auth.type] ?? auth.type

const connectors = []
for (const name of readdirSync(root, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort()) {
  const mod = await import(pathToFileURL(`${process.cwd()}/${root}/${name}/index.js`).href)
  connectors.push({ name, c: mod.default })
}

const live = connectors.filter(({ c }) => c.meta?.status === "live-tested").length
const lines = [
  "# Connector catalog",
  "",
  "<!-- Generated by scripts/catalog.mjs from each connector's `meta`. Do not edit by hand: run `pnpm catalog`. -->",
  "",
  `**${connectors.length} connectors** · ${live} live-tested · ${connectors.length - live} docs-based`,
  "",
  "| Connector | Import | Status | Auth | Actions | Docs |",
  "|---|---|---|---|---|---|",
  ...connectors.map(({ name, c }) => `| **${c.meta.title}** | \`connector-kit/${name}\` | ${c.meta.status} | ${authLabel(c.auth)} | ${Object.keys(c.actions).length} | [API docs](${c.meta.docsUrl}) |`),
  "",
  "## What the status means",
  "",
  "- **live-tested**: the actions were run against the real API with a real account.",
  "- **docs-based**: written from the provider's official documentation and tested against a fake server, but **not run against the real service**. It may contain small mistakes (a field name, a scope). Please [report them](https://github.com/itzzzzzzak/connector-kit/issues/new/choose). Verifying one against a real account and sending the result is one of the most useful contributions you can make: see [writing-connectors.md](writing-connectors.md).",
  "",
  "## Actions",
  "",
  ...connectors.flatMap(({ name, c }) => [
    `### ${c.meta.title} (\`${name}\`)`,
    "",
    c.meta.description,
    "",
    ...Object.entries(c.actions).map(([action, a]) => `- \`${action}\` (${a.effect}): ${a.description.split(/(?<=[.!?])\s/)[0]}`),
    "",
  ]),
]
const output = lines.join("\n")

if (check) {
  const current = existsSync("docs/connectors.md") ? readFileSync("docs/connectors.md", "utf8") : ""
  if (current !== output) {
    console.error("docs/connectors.md is out of date. Run `pnpm catalog`.")
    process.exit(1)
  }
  console.log(`catalog up to date (${connectors.length} connectors)`)
} else {
  writeFileSync("docs/connectors.md", output)
  console.log(`wrote docs/connectors.md (${connectors.length} connectors)`)
}
